apiVersion: v1
kind: Pod
metadata:
  name: myPod
spec:
  containers:
    - name: myfrondEnd
      image: nginx
      valumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
  # volume được gắn kết trong container
  # volume được gắn kết trong pod
  volumes:
    - name: mypd
      # connect pod with persistent volume claim by ( name in metadata of persistent-valume-cliam.yaml)
      persistentVolumeClassName:
        claimName: pvc-name
