apiVersion: v2
kind: Secret
metadata:
  name: tls-secret
  # required
  nameSpace: default
data:
  # required
  # base 64 encode (file contents, not file path/ location)
  tls.crt: Y2VydA==
  # required
  # base 64 encode (file contents, not file path/ location)
  tls.key: Y2VydA==
# specific type of secret call tls
type: kubernetes.io/tls
